favicon: /assets/img/identity/favicon.svg
primaryLogo: /assets/img/identity/primary-logo-light.svg
secondaryLogo: /assets/img/identity/secondary-logo.svg

main_menu_settings:
  menu_items:
    - title: About
      url: /about
    - title: History
      url: /history
    - title: Succession
      url: /lords-of-the-manor
    - title: State of the Claim
      url: /state-of-the-claim
    - title: Archives
      url: /archives
    - title: Research
      submenu_items:
        - title: Research ledger
          url: /research
        - title: Bibliography
          url: /bibliography
    - title: Explore
      submenu_items:
        - title: Map room
          url: /map-room
        - title: Dane John Gardens
          url: /gardens
        - title: FAQ
          url: /faq

footer_menu_settings:
  menu_items:
    - title: Terms of Use
      url: /terms-of-use
    - title: Privacy Notice
      url: /privacy-and-cookie-notice
    - title: Cookie Settings
      url: /privacy-and-cookie-notice#cookie-settings
      data:
        cookie-preferences:

footer_settings:
  footer_tagline: A website of the House of Basu-Howard
